### ISSUE TITLE
Error compiling 1.8.1 or current git (1.8.3)

### ISSUE THREAD

**Issue by sklages** [pashadag/Cnver#1]
edit: I mean version 0.8.1

Hi,

email cnver@cs.toronto.edu is not working, so I try this way:

I just wanted to compile cnver but ran into problems with both 1.8.1 and
current git.

git clone https://github.com/pashadag/Cnver.git

cd Cnver
./configure
make

[..]
concordancy_analysis.cpp:23:41: warning: ‘typedef’ was ignored in this
declaration [enabled by default]
 typedef enum dirEnum { FOR = 0, BACK = 1};
                                         ^
concordancy_analysis.cpp: In function ‘int main(int, char*_)’:
concordancy_analysis.cpp:203:58: error: ‘getopt’ was not declared in
this scope
  while ((ch = getopt(argc, argv, "pcf:b:u:l:t:d:r:m:n:i:")) != -1) {
                                                          ^
concordancy_analysis.cpp:212:19: error: ‘optarg’ was not declared in
this scope
     upperd = atoi(optarg);
                   ^
concordancy_analysis.cpp:238:65: error: ‘optind’ was not declared in
this scope
  if (!((upperd >= lowerd) && (lowerd >= 0) && (readLen > 0) && (optind
== argc ) )) {//should be no other parameter
                                                                 ^
make[3]: *_\* [concordancy_analysis.o] Error 1
make[3]: Leaving directory `/scratch/local/install/Cnver/src/cluster'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/scratch/local/install/Cnver/src'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/scratch/local/install/Cnver'
make: **\* [all] Error 2

After adding
# include<getopt.h> to concordancy_analysis.cpp I get the next one:

[..]
g++  -g -O2   -o concordancy_analysis  concordancy_analysis.o BGZF.o
BamReader.o BamWriter.o  -lz
if g++ -DHAVE_CONFIG_H -I. -I. -I../..     -g -O2 -MT
cluster_matepairs.o -MD -MP -MF ".deps/cluster_matepairs.Tpo" -c -o
cluster_matepairs.o cluster_matepairs.cpp; \
    then mv -f ".deps/cluster_matepairs.Tpo" ".deps/cluster_matepairs.Po";
else rm -f ".deps/cluster_matepairs.Tpo"; exit 1; fi
cluster_matepairs.cpp: In instantiation of ‘bool winScan<T>::load_line()
[with T = std::vectorstd::basic_string<char >]’:
cluster_matepairs.cpp:55:14:   required from ‘void
winScan<T>::incr(int&) [with T = std::vectorstd::basic_string<char >]’
cluster_matepairs.cpp:252:20:   required from here
cluster_matepairs.cpp:67:34: error: ‘make_T’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at
the point of instantiation [-fpermissive]
    buf.push_back(make_T(s, dummyT));
                                  ^
cluster_matepairs.cpp:84:16: note: ‘std::vectorstd::basic_string<char

> make_T(std::string&, std::vectorstd::basic_string<char >&)’ declared
> here, later in the translation unit
>  vector<string> make_T (string & s, vector<string> & dummy) {
>                 ^
> make[3]: **\* [cluster_matepairs.o] Fehler 1
> make[3]: Verlasse Verzeichnis '/tmp/cnver/Cnver/src/cluster'
> make[2]: **\* [all-recursive] Fehler 1
> make[2]: Verlasse Verzeichnis '/tmp/cnver/Cnver/src'
> make[1]: **\* [all-recursive] Fehler 1
> make[1]: Verlasse Verzeichnis '/tmp/cnver/Cnver'
> make: **\* [all] Fehler 2

This is Ubuntu 14.04 (64bit), g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2

Same results at work, homemade linux 64bit, g++ (GCC) 4.8.2

As I am not really familiar with C/C++ I assume that there are some
requisites missing?

Can you help?

Thanks,
Sven

**Comment by robinweide** [comment]
same problem here.

(running os x Yosemite)

**Comment by pashadag** [comment]
Sven used an older gcc 3.4.6, which fixed the problem.

**Comment by robinweide** [comment]
Hi,

I don’t know how to change the version of my gcc/compiler.

With kind regards,

Robin H. van der Weide

—
Robin H. van der Weide, BSc.
Master-student “Cancer, Stem Cells and Development (hons) | Computational complex genetics
06-30302055 | robinweide@gmail.com
Twitter: twitter.com/robinweide | LinkedIn: linkedin.com/in/robinvanderweide

**Comment by histamineblkr** [comment]
# Environment

On ubuntu 14.04 LTS 3.19.0-26-generic x86_64
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

## During Make Command, Following Errors Encountered

### Output

make  all-recursive
make[1]: Entering directory `/opt/cnver-0.8.1'
Making all in src
make[2]: Entering directory`/opt/cnver-0.8.1/src'
Making all in cluster
make[3]: Entering directory `/opt/cnver-0.8.1/src/cluster'
if g++ -DHAVE_CONFIG_H -I. -I. -I../..     -g -O2 -MT concordancy_analysis.o -MD -MP -MF ".deps/concordancy_analysis.Tpo" -c -o concordancy_analysis.o concordancy_analysis.cpp; \
    then mv -f ".deps/concordancy_analysis.Tpo" ".deps/concordancy_analysis.Po"; else rm -f ".deps/concordancy_analysis.Tpo"; exit 1; fi
In file included from concordancy_analysis.cpp:21:0:
../include/InputReader.h: In member function ‘bool InputReader::getNext(Map_t&)’:
../include/InputReader.h:40:117: warning: format ‘%u’ expects argument of type ‘unsigned int*’, but argument 3 has type ‘uint64_t* {aka long unsigned int*}’ [-Wformat=]
    int read_in = sscanf(sbuf.c_str(),"%u%c:<%d,%u,%*u>",&(mapt.read_id),&(mapt.orientation),&ref_num,&(mapt.ref_pos));
                                                                                                                     ^
../include/InputReader.h:40:117: warning: format ‘%u’ expects argument of type ‘unsigned int*’, but argument 6 has type ‘uint64_t* {aka long unsigned int*}’ [-Wformat=]
concordancy_analysis.cpp: At global scope:
concordancy_analysis.cpp:23:41: warning: ‘typedef’ was ignored in this declaration [enabled by default]
 typedef enum dirEnum { FOR = 0, BACK = 1};
                                         ^
concordancy_analysis.cpp: In function ‘int main(int, char**)’:
concordancy_analysis.cpp:203:58: error: ‘getopt’ was not declared in this scope
  while ((ch = getopt(argc, argv, "pcf:b:u:l:t:d:r:m:n:i:")) != -1) {
                                                          ^
concordancy_analysis.cpp:212:19: error: ‘optarg’ was not declared in this scope
     upperd = atoi(optarg);
                   ^
concordancy_analysis.cpp:238:65: error: ‘optind’ was not declared in this scope
  if (!((upperd >= lowerd) && (lowerd >= 0) && (readLen > 0) && (optind == argc ) )) {//should be no other parameter
                                                                 ^
make[3]: *** [concordancy_analysis.o] Error 1
make[3]: Leaving directory`/opt/cnver-0.8.1/src/cluster'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory `/opt/cnver-0.8.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/opt/cnver-0.8.1'
make: **\* [all] Error 2

## A Few Errors I Was Able to Fix

### Mismatched ints (uint64_t)

sscanf in src/include/InputReader.h
documentation [here](http://stackoverflow.com/questions/6993132/format-specifiers-for-uint8-t-uint16-t)
I fixed this by importing: `#include <inttypes.h>`
and using the macros of SCNd64
Line::40
`int read_in = sscanf(sbuf.c_str(), "%" SCNd64 "%c:<%d,%" SCNd64 ",%*u>",&(mapt.read_id),&(mapt.orientation),&ref_num,&(mapt.ref_pos));`

### For getopt, optarg, and optind

In src/include/InputReader.h
I included this: `#include <unistd.h>`
documentation [here](http://pubs.opengroup.org/onlinepubs/009695399/functions/getopt.html)

## Make Again

### Output

make  all-recursive
make[1]: Entering directory `/opt/cnver-0.8.1'
Making all in src
make[2]: Entering directory`/opt/cnver-0.8.1/src'
Making all in cluster
make[3]: Entering directory `/opt/cnver-0.8.1/src/cluster'
if g++ -DHAVE_CONFIG_H -I. -I. -I../..     -g -O2 -MT cluster_matepairs.o -MD -MP -MF ".deps/cluster_matepairs.Tpo" -c -o cluster_matepairs.o cluster_matepairs.cpp; \
    then mv -f ".deps/cluster_matepairs.Tpo" ".deps/cluster_matepairs.Po"; else rm -f ".deps/cluster_matepairs.Tpo"; exit 1; fi
cluster_matepairs.cpp: In instantiation of ‘bool winScan<T>::load_line() [with T = std::vector<std::basic_string<char> >]’:
cluster_matepairs.cpp:55:14:   required from ‘void winScan<T>::incr(int&) [with T = std::vector<std::basic_string<char> >]’
cluster_matepairs.cpp:252:20:   required from here
cluster_matepairs.cpp:67:34: error: ‘make_T’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
    buf.push_back(make_T(s, dummyT));
                                  ^
cluster_matepairs.cpp:84:16: note: ‘std::vector<std::basic_string<char> > make_T(std::string&, std::vector<std::basic_string<char> >&)’ declared here, later in the translation unit
 vector<string> make_T (string & s, vector<string> & dummy) {
                ^
make[3]: *** [cluster_matepairs.o] Error 1
make[3]: Leaving directory`/opt/cnver-0.8.1/src/cluster'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory `/opt/cnver-0.8.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/opt/cnver-0.8.1'
make: **\* [all] Error 2

### At this point I have to move on and finish my work, but hopefully the above fixes are of some use.

**Comment by histamineblkr** [comment]
When I have a little more time I can git clone this repository, make the fixes above, and create a pull request. Let me know if that would be better.

**Comment by pashadag** [comment]
Thanks, that would be great!

**Comment by histamineblkr** [comment]
I will try to get to that this week. I don't run Ubuntu at home so I have to use the computer at work to create the repository and then create the pull request. 
Do I use your public github and make pull requests there? There is no special permission requirements to create a pull request?

**Comment by pashadag** [comment]
Not sure exactly -- hopefully it works as you say, or at least I can see and approve the pull request.

**Comment by Toseph** [comment]
Just wanted to report this still seems to be an open issue. Please specify which version of GCC to be used in a prerequisite section as it is not clear. Thanks. 

`cluster_matepairs.cpp:67:34: error: ‘make_T’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
    buf.push_back(make_T(s, dummyT));`
